reusable_string!(BUF_VALIDATE_FIELD, "(buf.validate.field)");
reusable_string!(CONST_, "const");
reusable_string!(CEL);
reusable_string!(LEN);
reusable_string!(MAX_LEN);
reusable_string!(MIN_LEN);
reusable_string!(REQUIRED);
reusable_string!(IN_, "in");
reusable_string!(NOT_IN);
reusable_string!(CONTAINS);
reusable_string!(NOT_CONTAINS);
reusable_string!(SUFFIX);
reusable_string!(PREFIX);
reusable_string!(PATTERN);
reusable_string!(IP);
reusable_string!(IPV4);
reusable_string!(IPV6);
reusable_string!(LT);
reusable_string!(LTE);
reusable_string!(GT);
reusable_string!(GTE);
reusable_string!(ID);
reusable_string!(MESSAGE);
reusable_string!(EXPRESSION);
reusable_string!(IGNORE);
